export const SET_EMPLOYEES = 'SET_EMPLOYEES';
export const SET_EMPLOYEES_LOADING = 'SET_EMPLOYEES_LOADING';
export const SET_GROUPS = 'SET_GROUPS';
export const SET_GROUPS_LOADING = 'SET_GROUPS_LOADING';
